### ISSUE TITLE
Mod Crashes on Startup

### ISSUE THREAD

**Issue by Archmage-Erebus** [artynova/mediaworks#16]
Error Log

Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod discovery failed!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:197)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod discovery failed!
	at net.fabricmc.loader.impl.discovery.ModDiscoverer.lambda$discoverMods$1(ModDiscoverer.java:147)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.discovery.ModDiscoverer.discoverMods(ModDiscoverer.java:147)
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:215)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
	... 9 more
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Error analyzing [C:\Users\Username\MultiMC\MultiMC\instances\1.19.2 Fabric\.minecraft\mods\mediaworks-fabric-1.19.2-1.0.5.jar]: java.util.zip.ZipException: zip file is empty
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:484)
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:540)
	at java.base/java.util.concurrent.ForkJoinTask.reportExecutionException(ForkJoinTask.java:580)
	at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:993)
	at net.fabricmc.loader.impl.discovery.ModDiscoverer.discoverMods(ModDiscoverer.java:144)
	... 11 more
Caused by: java.lang.RuntimeException: Error analyzing [C:\Users\Username\MultiMC\MultiMC\instances\1.19.2 Fabric\.minecraft\mods\mediaworks-fabric-1.19.2-1.0.5.jar]: java.util.zip.ZipException: zip file is empty
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:288)
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:237)
	at java.base/java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:110)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1311)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1841)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1806)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.util.zip.ZipException: zip file is empty
	at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1615)
	at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1396)
	at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1491)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1329)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1292)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:710)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:243)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:172)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:186)
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.computeJarFile(ModDiscoverer.java:309)
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:278)
	... 7 more

**Comment by Archmage-Erebus** [comment]
I honestly have no idea what causing it to break like this

**Comment by artynova** [comment]
Greetings! Apologies for the delayed response. I was unable to reproduce this error with Mediaworks, but, purely by chance, encountered a similar problem with a different mod. What helped was removing it manually from the mods folder and reinstalling it.

As far as I was able to understand, this error with an empty archive file happens due to a problem during installation, so please try deleting the mod file at C:\Users\Username\MultiMC\MultiMC\instances\1.19.2 Fabric.minecraft\mods\mediaworks-fabric-1.19.2-1.0.5.jar and reinstalling it. Also, you could try installing Mediaworks and all its dependencies into a fresh profile and see whether it launches.

Without further information, this is all the advice I can give you for now. Have a good day!

**Comment by artynova** [comment]
Greetings! You have not engaged with this issue for a long time. I hope your inactivity means that you successfully resolved it. Since I could not reproduce the issue and it seems no longer relevant to you, I will be closing it as stale in about a week unless you indicate that it is still relevant.
